### ISSUE TITLE
Barra de busca e seletor não acompanham o crescimento do container

### ISSUE THREAD

**Issue by PedroClainUni** [BSI-PCS-2021-2/digital-wave-games#21]
O objetivo é a barra de busca da pagina catalogo acompanhar o crescimento do container

![Screenshot_20211208-232716_Samsung Internet](https://user-images.githubusercontent.com/94701105/145323710-54c43166-2bf0-4640-9db5-380c5f471ded.jpg)

No modo mobile elas devem preencher toda a largura do container

![Screenshot_20211208-232629_Samsung Internet](https://user-images.githubusercontent.com/94701105/145323839-c8470f85-1c5f-499b-962a-e163d5fd03ea.jpg)

**Comment by brensio** [comment]
Corrigido no PR #34
