### ISSUE TITLE
Cor errada em select input

### ISSUE THREAD

**Issue by PedroClainUni** [BSI-PCS-2021-2/digital-wave-games#28]
A cor deveria ser branca (ou outra mais  clara) ao selecionar 

![Screenshot_20211209-161831_Samsung Internet](https://user-images.githubusercontent.com/94701105/145462194-11b4aead-04b5-4b21-b983-3d15b3f669a8.jpg)

**Comment by brensio** [comment]
Corrigido no PR #30 , conforme a imagem:

![image](https://user-images.githubusercontent.com/57153252/145655747-28f31d43-d796-41d5-bc6c-8508bbc15d5e.png)
