### ISSUE TITLE
Botão "adicionado" da página catálogo altera o tamanho do card

### ISSUE THREAD

**Issue by PedroClainUni** [BSI-PCS-2021-2/digital-wave-games#36]
![Captura de tela_2021-12-15_17-22-00](https://user-images.githubusercontent.com/94701105/146259583-4e8e4739-ea03-4075-be1d-39b031a42424.png)

**Comment by brensio** [comment]
Corrigido aplicando uma borda no botão do carrinho.

**Comment by brensio** [comment]
Estou reabrindo porque percebi que na resolução 720p o problema persiste, apesar de não acontecer mais em 1080p.

**Comment by brensio** [comment]
Defini uma largura padrão entre os dois estados do botão para evitar a alteração.
